runtime: go114
instance_class: F2

handlers:

# All URLs are handled by the Go application script
- url: /.*
  script: _go_app
skip_files:
  - node_modules/
  - src/
  - .vscode/
  - package-lock.json
  - README.md
  - webpack.config.js
